# GitHub Actions workflow for Render.com deployment
name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_export.txt
    
    - name: Run tests (optional)
      run: |
        # Add your test commands here
        python -c "import render_app; print('App imports successfully')"
    
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment to Render will be triggered automatically"
        echo "Make sure to set TELEGRAM_BOT_TOKEN in Render dashboard"